apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: install-dependencies
      taskRef:
        name: npm-install
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: run-unit-tests
      runAfter:
        - install-dependencies
      taskRef:
        name: jasmine-test
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-image
      runAfter:
        - run-unit-tests
      taskRef:
        name: build-task-name # e.g., buildah or kaniko
      workspaces:
        - name: source
          workspace: shared-workspace
